server.port=${SERVER_PORT:8082}
spring.application.name=donation-service

spring.datasource.url=${DB_URL:${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/donation_db}}
spring.datasource.username=${DB_USERNAME:${SPRING_DATASOURCE_USERNAME:root}}
spring.datasource.password=${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:root123}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.api-key=${APP_API_KEY:donation-service-secret-key}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info
